### ISSUE TITLE
Facing issue in Exercise 1 Task 3 step 27, SQL management login.

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Building-a-resilient-IaaS-architecture#91] opened 2022-01-20 14:34 UTC
In Exercise 1 Task 3 step 27 we are facing a login issue. We are facing this issue very often I have tried it in 3 environments out of 3 we faced the below issue in two environments.

![image](https://user-images.githubusercontent.com/66515706/150356583-2dde6f48-51fc-45d3-b3d8-7523eaf1b8ff.png)

**Comment by DawnmarieDesJardins** [comment] 2022-01-28 21:12
@KitSkin - Hi Kit, any update for us on this one?

**Comment by KitSkin** [comment] 2022-01-31 15:20
Hi @anushabc,

Assuming these are not just a typo or incorrectly putting in the login information, the best guidance in these situations is to deploy the SQL server again (after removing it first).  Restarting the server or service may be enough if there was an issue with the server connecting.

I have not been able to reliably reproduce this error more than once in a dozen deployments.  In this scenario, there was an underlying deployment error.  

Thank you,
-Kit

**Comment by DawnmarieDesJardins** [comment] 2022-02-03 17:28
@anushabc 
Hello!  Please advise if you were able to move forward with the lab given the advise above.

**Comment by anushabc** [comment] 2022-02-08 17:32
Hi @DawnmarieDesJardins, we tested the lab and didn't encounter it we can close the issue

**Comment by DawnmarieDesJardins** [comment] 2022-02-08 17:45
Thanks @anushabc - have a wonderful day!

**Comment by mattboothman** [comment] 2022-03-20 19:13
We randomly have this. Either SQLVM1 or SQLVM2 will reject logins.

**Comment by DawnmarieDesJardins** [comment] 2022-03-21 16:21
Reopening issue for further investigation.

**Comment by karthikkc24** [comment] 2022-03-22 11:15
We are facing this issue very often. We have tried it in multiple environments. Still, we have an issue with connecting to Database Engine to SQLVM1 in SSMA.

Can you please check this ASAP and provide an update?

**Comment by mattboothman** [comment] 2022-03-23 07:07
```powershell
# The SPNs seem to end up in the wrong containers (COMPUTERNAME) as opposed to Domain user
# This is a bit of a hack to make sure it is straight. 
# See also: https://support.microsoft.com/en-sg/help/811889/how-to-troubleshoot-the-cannot-generate-sspi-context-error-message
Write-Output "Resetting SPNs"
$dnsDomain = $env:USERDNSDOMAIN
$domain = $env:USERDOMAIN
$user = $env:USERNAME
$computer = $env:COMPUTERNAME
SetSPN -s "MSOLAPSvc.3/$computer.$dnsDomain"    "$domain\$computer$"
SetSPN -s "MSOLAPSvc.3/$computer"               "$domain\$computer$"
SetSPN -d "MSSQLSvc/$computer.$dnsDomain"       "$domain\$computer$"
SetSPN -s "MSSQLSvc/$computer.$dnsDomain"       "$domain\$user"
SetSPN -d "MSSQLSvc/$computer.$dnsDomain`:1433" "$domain\$computer$"
SetSPN -s "MSSQLSvc/$computer.$dnsDomain`:1433" "$domain\$user"
```

This part of the sql-wrapped script seems to thing that the logged-in user is a domain user. With a local user, the `$env:USERDNSDOMAIN` is not defined so it emits a bunch of errors

```
SetSPN : Ldap Error(0x51 -- Server Down): ldap_connect
At line:68 char:1
+ SetSPN -s "MSOLAPSvc.3/$computer.$dnsDomain"    "$domain\$computer$"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ldap Error(0x51...): ldap_connect:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Failed to retrieve DN for domain "" : 0x00000051
Warning: No valid targets specified, reverting to current domain.
FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x0000054B
Unable to locate account SQLVM1$
SetSPN : Ldap Error(0x51 -- Server Down): ldap_connect
At line:69 char:1
+ SetSPN -s "MSOLAPSvc.3/$computer"               "$domain\$computer$"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ldap Error(0x51...): ldap_connect:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Failed to retrieve DN for domain "" : 0x00000051
Warning: No valid targets specified, reverting to current domain.
FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x0000054B
Unable to locate account SQLVM1$
SetSPN : FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x0000054B
At line:70 char:1
+ SetSPN -d "MSSQLSvc/$computer.$dnsDomain"       "$domain\$computer$"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FindDomainForAc...alue 0x0000054B:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Unable to locate account SQLVM1$
SetSPN : Ldap Error(0x51 -- Server Down): ldap_connect
At line:71 char:1
+ SetSPN -s "MSSQLSvc/$computer.$dnsDomain"       "$domain\$user"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ldap Error(0x51...): ldap_connect:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Failed to retrieve DN for domain "" : 0x00000051
Warning: No valid targets specified, reverting to current domain.
FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x0000054B
Unable to locate account demouser
SetSPN : FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x0000054B
At line:72 char:1
+ SetSPN -d "MSSQLSvc/$computer.$dnsDomain`:1433" "$domain\$computer$"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FindDomainForAc...alue 0x0000054B:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Unable to locate account SQLVM1$
SetSPN : Ldap Error(0x51 -- Server Down): ldap_connect
At line:73 char:1
+ SetSPN -s "MSSQLSvc/$computer.$dnsDomain`:1433" "$domain\$user"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ldap Error(0x51...): ldap_connect:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
Failed to retrieve DN for domain "" : 0x00000051
Warning: No valid targets specified, reverting to current domain.
FindDomainForAccount: Call to DsGetDcNameWithAccountW failed with return value 0x0000054B
Unable to locate account demouser
```

If the DSNs need to be set appropriately, then the computer likely needs to be joined to the domain first, then this script should be run under the context of a domain user.

This set of errors are always present because of the user context.

**Comment by mattboothman** [comment] 2022-03-23 07:15
The next set of errors, no always present, hppen because the SQL Server instance is not always up when the commands get executed:

```powershell
Exception setting "LoginMode": "Failed to connect to server Localhost."
At line:34 char:1
+ $sqlesq.Settings.LoginMode = [Microsoft.SqlServer.Management.Smo.Serv ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
Exception setting "DefaultFile": "Failed to connect to server Localhost."
At line:35 char:1
+ $sqlesq.Settings.DefaultFile = $data
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
Exception setting "DefaultLog": "Failed to connect to server Localhost."
At line:36 char:1
+ $sqlesq.Settings.DefaultLog = $logs
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
Exception setting "BackupDirectory": "Failed to connect to server Localhost."
At line:37 char:1
+ $sqlesq.Settings.BackupDirectory = $backups
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
Exception calling "Alter" with "0" argument(s): "Alter failed for Server 'Localhost'. "
At line:38 char:1
+ $sqlesq.Alter()
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FailedOperationException
Invoke-Sqlcmd : Login failed for user 'SQLVM1\demouser'.
At line:46 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
PS>TerminatingError(Invoke-Sqlcmd): ""
Invoke-Sqlcmd : 
At line:46 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserException
    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
Invoke-Sqlcmd : Login failed for user 'SQLVM1\demouser'.
At line:47 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
PS>TerminatingError(Invoke-Sqlcmd): ""
Invoke-Sqlcmd : 
At line:47 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserException
    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
Invoke-Sqlcmd : Login failed for user 'SQLVM1\demouser'.
At line:51 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "CR ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
PS>TerminatingError(Invoke-Sqlcmd): ""
Invoke-Sqlcmd : 
At line:51 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "CR ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserException
    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
Invoke-Sqlcmd : Login failed for user 'SQLVM1\demouser'.
At line:52 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
PS>TerminatingError(Invoke-Sqlcmd): ""
Invoke-Sqlcmd : 
At line:52 char:1
+ Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "AL ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserException
    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
```

These errors relate to these lines in the script:

```powershell
# Setup the data, backup and log directories as well as mixed mode authentication
Write-Output "Set up data, backup and log directories in SQL, plus mixed-mode auth"
Import-Module "sqlps" -DisableNameChecking
[System.Reflection.Assembly]::LoadWithPartialName("Microsoft.SqlServer.Smo")
$sqlesq = new-object ('Microsoft.SqlServer.Management.Smo.Server') Localhost
$sqlesq.Settings.LoginMode = [Microsoft.SqlServer.Management.Smo.ServerLoginMode]::Mixed
$sqlesq.Settings.DefaultFile = $data
$sqlesq.Settings.DefaultLog = $logs
$sqlesq.Settings.BackupDirectory = $backups
$sqlesq.Alter() 

# Restart the SQL Server service
Write-Output "Restart SQL"
Restart-Service -Name "MSSQLSERVER" -Force

# Re-enable the sa account and set a new password to enable login
Write-Output "Re-enable 'sa' account, and set password to $password"
Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "ALTER LOGIN sa ENABLE" 
Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "ALTER LOGIN sa WITH PASSWORD = '$password'"

#Add local administrators group as sysadmin
Write-Output "Add local admins as sysadmin"
Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "CREATE LOGIN [BUILTIN\Administrators] FROM WINDOWS"
Invoke-Sqlcmd -ServerInstance Localhost -Database "master" -Query "ALTER SERVER ROLE sysadmin ADD MEMBER [BUILTIN\Administrators]"
```

From experience, this is completely random. Sometimes SQL is started and everything works fine, others it isn't. Sometimes we get issues with SQL1, others SQL2. I guess it's possible it would affect both during the same "session".

Looking at the event log, SQL starts and stops a number of times during the first start up. You might be able to fix it by adding a check to see if SQL is up before trying to connect to it. I'm not sure you could guarantee that SQL would stay up once confirmed, though.

**Comment by mattboothman** [comment] 2022-03-23 07:16
Disclaimer: Our usage relates to files keps on https://cloudworkshop.blob.core.windows.net/building-resilient-iaas-architecture/lab-resources/june-2020-update/

**Comment by DawnmarieDesJardins** [comment] 2022-03-24 22:05
Closing issue with merge of PR #94

**Comment by mattboothman** [comment] 2022-04-18 07:52
Unfortunately, this still appears to be problematic.

I don't mind testing before you close tickets?

**Comment by DawnmarieDesJardins** [comment] 2022-04-18 15:31
Reopening issue and reassigning.

**Comment by sadukie** [comment] 2022-04-19 20:31
@DawnmarieDesJardins I talked with @timahenning about this. We're going to see if we can track this issue down and fix it as part of the scheduled test/fix.

**Comment by DawnmarieDesJardins** [comment] 2022-04-29 16:15
Closing issue with merge of PR #99

**Closed by DawnmarieDesJardins** 2022-04-29 16:15 UTC
