### ISSUE TITLE
Ex-1 T-3 S-32 Not able to see ContosoInsurance Database.

### ISSUE THREAD

**Issue by rcy0228** [microsoft/MCW-Building-a-resilient-IaaS-architecture#104] opened 2023-02-09 14:43 UTC
Hi @benstegink, in [Exercise-1/Task-3/Step-37](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Building%20a%20resilient%20IaaS%20architecture.md#task-3-configure-ha-for-the-sql-server-tier), Contoso insurance database is not showing up while creating Availability Group. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/104890759/217836662-b34de834-3360-46eb-9f4b-5e0c7d59de92.png)

**Comment by DawnmarieDesJardins** [comment] 2023-02-10 18:38
@rcy0228 - Thanks for reaching out.  We will assign the issue as soon as an author is available.

**Comment by Divyasri199** [comment] 2023-02-14 04:32
> @rcy0228 - Thanks for reaching out. We will assign the issue as soon as an author is available.

Hello @DawnmarieDesJardins any update on this?

**Comment by DawnmarieDesJardins** [comment] 2023-02-14 18:53
@Divyasri199 - Hello.  Nothing yet, my apologies. I will assign an author to review as soon as I am able.

**Comment by Divyasri199** [comment] 2023-02-21 06:34
Hello @DawnmarieDesJardins, we have also observed the PowerShell script to import the database to SQL server management studio is failing. I am attaching the transcript files here for your reference.

[deploy-sql-wrapper-log.txt](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/files/10790343/deploy-sql-wrapper-log.txt)
[deploy-sqlvm-log2.txt](https://github.com/microsoft/MCW-Building-a-resilient-IaaS-architecture/files/10790344/deploy-sqlvm-log2.txt)

We have also tried to run the script **deploy-sqlvm-wrapper.ps1** manually, but we got the below mentioned error:

```
System.Data.SqlClient.SqlError: The media family on device 'D:\ContosoInsurance.bak' is 
incorrectly formed. SQL Server cannot process this media family.
    + CategoryInfo          : InvalidOperation: (:) [Restore-SqlDatabase], SmoException
    + FullyQualifiedErrorId : ExecutionFailed,Microsoft.SqlServer.Management.PowerShell.Restor 
   eSqlDatabaseCommand
    + PSComputerName        : SQLVM1
 ```
Please consider this as **Sev A** and do the needful. We have the scheduled labs in this week.

**Comment by DawnmarieDesJardins** [comment] 2023-03-06 19:10
Added Sarah for visibility

**Comment by benstegink** [comment] 2023-03-09 00:10
@Divyasri199 I just went through this and I'm not finding any issues. Looking at the logs above, it looks like it may have maybe had some issues with the user creds or the domain. So, a couple things to check:

1. Did you reboot all 6 VMS after the deployment to make sure they picked up the new DNS settings and thus be able to contact the domain controllers
2. When you set everything up and logged in via Bastion, did you use the username demouser@contoso.com (in that format)

**Comment by DawnmarieDesJardins** [comment] 2023-03-17 18:02
No additional comments, closing issue.  Please reopen if necessary.

**Comment by Divyasri199** [comment] 2023-03-31 14:34
Hello @DawnmarieDesJardins and @benstegink ,

Sorry for the delay in response.

Yes, We have tried with rebooting the VMs, here the few points which we followed to resolve the issue :

**Issue 1 :** Unavailability of Contoso Insurance database while creating the Availability group in E1/T3

**Resolution :** We have observed the script to import the database is getting failed in SQL VMs, we figure out that the script is failing in few environment where the import database was failing with random error with user creds. this is not happening in all environment but failing for few. Hence we have updated the script to add more checkpoint to make sure the database with get restored.

**Issue** 2: We were having issue in replicating the VMs because of Automation account with pre-created account

Resolution: We have added steps to created the automation account as the new automation account will work fine.

Also there have a lot of old UI screenshots available.. we need to update the screenshots as well. 

@benstegink , it would be great if you deploy few environment together and try as its is failing for almost 3 out of 5. 

Thanks

**Comment by benstegink** [comment] 2023-04-12 12:26
@Divyasri199 I put a longer delay in this recent update to help with Issue 1 creating the SQL database. I also confirmed that those credential errors in the wrapper log were due to something else, so I fixed that as well. I also deployed this maybe 20 or 25 times yesterday and never had an issue with it creating the database. So hopefully that fixes that issue and it will successfully create the database for you know. You'll just need to wait for this latest pull request to be approved before trying again.

**Comment by benstegink** [comment] 2023-04-12 12:34
@Divyasri199 can you provide more details on that second issue referenced above as well? The automation account used for failover should be getting created by the students as they do the lab, not pre-created. So I'm not sure what's getting precreated related to the automation account that's causing the issues. Thanks!

**Comment by DawnmarieDesJardins** [comment] 2023-04-17 21:00
@Divyasri199 - Hello!  Checking in for additional information for our author, Ben.  Thanks

**Comment by DawnmarieDesJardins** [comment] 2023-04-20 17:07
No additional comments, closing issue.

**Closed by DawnmarieDesJardins** 2023-04-20 17:07 UTC
